// © 2020 Google, Ecma International

// Polyfill Intl.getSupportedCurrencies
if (Intl.getSupportedCurrencies == undefined) {
  Intl.getSupportedCurrencies = function() {
    const ATOZ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const CURRENCIES_IN_CLDR = [ 
      // DATA from CLDR
      // Generated by  
      // file="https://raw.githubusercontent.com/unicode-org/cldr/master/common/validity/currency.xml"
      // curl $file 2> /dev/null | egrep -e " *([A-Z]{3}( [A-Z]{3})*)$" | \ 
      //    sed -e 's/^[[:space:]]*/"/g'|sed -e 's/ /", "/g' |sed -e 's/$/",/g'|tr '\n' ' ' 
      "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM",
      "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN",
      "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY", "COP", "CRC", "CUC",
      "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR",
      "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD",
      "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD",
      "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT",
      "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK",
      "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN",
      "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN",
      "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK",
      "SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STN", "SYP", "SZL", "THB", "TJS",
      "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU",
      "UZS", "VES", "VND", "VUV", "WST", "XAF", "XCD", "XOF", "XPF", "YER", "ZAR",
      "ZMW", "ADP", "AFA", "ALK", "AOK", "AON", "AOR", "ARA", "ARL~M", "ARP",
      "ATS", "AZM", "BAD", "BAN", "BEC", "BEF", "BEL", "BGL~M", "BGO", "BOL",
      "BOP", "BOV", "BRB~C", "BRE", "BRN", "BRR", "BRZ", "BUK", "BYB", "BYR",
      "CHE", "CHW", "CLE~F", "CNH", "CNX", "COU", "CSD", "CSK", "CYP", "DDM",
      "DEM", "ECS", "ECV", "EEK", "ESA~B", "ESP", "FIM", "FRF", "GEK", "GHC",
      "GNS", "GQE", "GRD", "GWE", "GWP", "HRD", "IEP", "ILP", "ILR", "ISJ", "ITL",
      "KRH", "KRO", "LTL", "LTT", "LUC", "LUF", "LUL", "LVL", "LVR", "MAF", "MCF",
      "MDC", "MGF", "MKN", "MLF", "MRO", "MTL", "MTP", "MVP", "MXP", "MXV", "MZE",
      "MZM", "NIC", "NLG", "PEI", "PES", "PLZ", "PTE", "RHD", "ROL", "RUR", "SDD",
      "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "SVC", "TJR", "TMM", "TPE", "TRL",
      "UAK", "UGS", "USN", "USS", "UYI", "UYP", "UYW", "VEB", "VEF", "VNN", "XAG",
      "XAU", "XBA~D", "XDR", "XEU", "XFO", "XFU", "XPD", "XPT", "XRE", "XSU",
      "XTS", "XUA", "YDD", "YUD", "YUM~N", "YUR", "ZAL", "ZMK", "ZRN", "ZRZ",
      "ZWD", "ZWL", "ZWR", "XXX"
    ];

    const isSupported = function(currency) {
      try {
        let nf = new Intl.NumberFormat("en",
            {style: "currency", currencyDisplay: "name", currency});
        let fmt = nf.format(123);
        if (fmt.substring(0, 3) != currency && fmt.substring(fmt.length - 3) != currency) {
          return true;
        }
      } catch (e) {
        // cause exception
      }
      return false;
    };

    var r = [];
    CURRENCIES_IN_CLDR.forEach(function(item) {
      if (item.length == 3) {
        if (isSupported(item)) {
          r.push(item);
        }
      } else if (item.length == 5 && item.indexOf("~") == 3) {
        start = ATOZ.indexOf(item[2]);
        end = ATOZ.indexOf(item[4]);
        for (var i = start; i <= end; i++) {
          let c = item.substring(0, 2) + ATOZ[i];
          if (isSupported(c)) {
            r.push(c);
          }
        }
      }
    });
    return r;
  };
}
