// © 2020 Google, Ecma International

// Polyfill Intl.getSupportedRegions
if (Intl.getSupportedRegions == undefined) {
  Intl.getSupportedRegions = function() {
    const ATOZ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const _0TO9 = "0123456789";
    const REGIONS_IN_CLDR = [
      // DATA from CLDR
      // Generated by
      // file="https://raw.githubusercontent.com/unicode-org/cldr/master/common/validity/region.xml"
      // curl $file 2> /dev/null  | egrep -e " *(([A-Z]{2}(~[A-Z])?( ([A-Z]{2})(~[A-Z])?)*)|(([0-9]{3}(~[0-9])?( ([0-9]{3})(~[0-9])?)*)))$"  | \
      // sed -e 's/^[[:space:]]*/"/g'|sed -e 's/ /", "/g' |sed -e 's/$/",/g'|tr '\n' ' '
      "AC~G", "AI", "AL~M", "AO", "AQ~U", "AW~X", "AZ", "BA~B", "BD~J", "BL~O",
      "BQ~T", "BV~W", "BY~Z", "CA", "CC~D", "CF~I", "CK~P", "CR", "CU~Z", "DE",
      "DG", "DJ~K", "DM", "DO", "DZ", "EA", "EC", "EE", "EG~H", "ER~T", "FI~K",
      "FM", "FO", "FR", "GA~B", "GD~I", "GL~N", "GP~U", "GW", "GY", "HK", "HM~N",
      "HR", "HT~U", "IC~E", "IL~O", "IQ~T", "JE", "JM", "JO~P", "KE", "KG~I",
      "KM~N", "KP", "KR", "KW", "KY~Z", "LA~C", "LI", "LK", "LR~V", "LY", "MA",
      "MC~H", "MK~Z", "NA", "NC", "NE~G", "NI", "NL", "NO~P", "NR", "NU", "NZ",
      "OM", "PA", "PE~H", "PK~N", "PR~T", "PW", "PY", "QA", "RE", "RO", "RS", "RU",
      "RW", "SA~E", "SG~O", "SR~T", "SV", "SX~Z", "TA", "TC~D", "TF~H", "TJ~O",
      "TR", "TT", "TV~W", "TZ", "UA", "UG", "UM", "US", "UY~Z", "VA", "VC", "VE",
      "VG", "VI", "VN", "VU", "WF", "WS", "XK", "YE", "YT", "ZA", "ZM", "ZW",
      "XA~B", "001~3", "005", "009", "011", "013~5", "017~9", "021", "029", "030",
      "034~5", "039", "053~4", "057", "061", "142~3", "145", "150~1", "154~5",
      "202", "419", "EU", "EZ", "QO", "UN", "AN", "BU", "CS", "DD", "FX", "NT",
      "QU", "SU", "TP", "YD", "YU", "ZR", "AA", "QM~N", "QP~T", "QV~Z", "XC~J",
      "XL~Z", "ZZ"
    ];

    const isSupported = function(region) {
      // always return true for now.
      return true;
    };

    var r = [];
    REGIONS_IN_CLDR.forEach(function(region) {
      if (region.length == 2 || region.length == 3) {
        if (isSupported(region)) { r.push(region); }
      } else if (region.length == 4  && region.indexOf("~") == 2) {
        start = ATOZ.indexOf(region[1]);
        end = ATOZ.indexOf(region[3]);
        for (var i = start; i <= end; i++) {
          let reg = region[0] + ATOZ[i];
          if (isSupported(reg)) { r.push(reg); }
        }
      } else if (region.length == 5  && region.indexOf("~") == 3) {
        start = _0TO9.indexOf(region[2]);
        end = _0TO9.indexOf(region[4]);
        for (var i = start; i <= end; i++) {
          let reg = region.substring(0, 2) + _0TO9[i];
          if (isSupported(reg)) { r.push(reg); }
        }
      }
    });
    return r;
  };
}
