// © 2020 Google, Ecma International

// Polyfill Intl.getSupportedScripts
if (Intl.getSupportedScripts == undefined) {
  Intl.getSupportedScripts = function() {
    const ATOZ = "abcdefghijklmnopqrstuvwxyz";
    const SCRIPTS_IN_CLDR = [
      // DATA from CLDR
      // Generated by
      // file="https://raw.githubusercontent.com/unicode-org/cldr/master/common/validity/script.xml"
      // curl $file 2> /dev/null  |egrep -e "[A-Z][a-z]{3}(~[a-z])?( [A-Z][a-z]{3}(~[a-z])?)*$"  |\
      //   sed -e 's/^[[:space:]]*/"/g'|sed -e 's/ /", "/g' |sed -e 's/$/",/g'|tr '\n' ' '
      "Adlm", "Aghb", "Ahom", "Arab", "Armi", "Armn", "Avst", "Bali", "Bamu",
      "Bass", "Batk", "Beng", "Bhks", "Bopo", "Brah~i", "Bugi", "Buhd", "Cakm",
      "Cans", "Cari", "Cham", "Cher", "Chrs", "Copt", "Cprt", "Cyrl", "Deva",
      "Diak", "Dogr", "Dsrt", "Dupl", "Egyp", "Elba", "Elym", "Ethi", "Geor",
      "Glag", "Gong", "Gonm", "Goth", "Gran", "Grek", "Gujr", "Guru", "Hanb",
      "Hang", "Hani", "Hano", "Hans~t", "Hatr", "Hebr", "Hira", "Hluw", "Hmng",
      "Hmnp", "Hrkt", "Hung", "Ital", "Jamo", "Java", "Jpan", "Kali", "Kana",
      "Khar", "Khmr", "Khoj", "Kits", "Knda", "Kore", "Kthi", "Lana", "Laoo",
      "Latn", "Lepc", "Limb", "Lina~b", "Lisu", "Lyci", "Lydi", "Mahj", "Maka",
      "Mand", "Mani", "Marc", "Medf", "Mend", "Merc", "Mero", "Mlym", "Modi",
      "Mong", "Mroo", "Mtei", "Mult", "Mymr", "Nand", "Narb", "Nbat", "Newa",
      "Nkoo", "Nshu", "Ogam", "Olck", "Orkh", "Orya", "Osge", "Osma", "Palm",
      "Pauc", "Perm", "Phag", "Phli", "Phlp", "Phnx", "Plrd", "Prti", "Rjng",
      "Rohg", "Runr", "Samr", "Sarb", "Saur", "Sgnw", "Shaw", "Shrd", "Sidd",
      "Sind", "Sinh", "Sogd", "Sogo", "Sora", "Soyo", "Sund", "Sylo", "Syrc",
      "Tagb", "Takr", "Tale", "Talu", "Taml", "Tang", "Tavt", "Telu", "Tfng",
      "Tglg", "Thaa", "Thai", "Tibt", "Tirh", "Ugar", "Vaii", "Wara", "Wcho",
      "Xpeo", "Xsux", "Yezi", "Yiii", "Aran", "Qaag", "Zanb", "Zinh", "Zmth",
      "Zsye", "Zsym", "Zxxx", "Zyyy", "Qaai", "Qaaa~f", "Qaah", "Qaaj~p",
      "Qaaq~z", "Qaba~x", "Zzzz"
    ];

    const isSupported = function(script) {
      return true;  // TODO Need to define the "support"
    };

    var r = [];
    SCRIPTS_IN_CLDR.forEach(function(script) {
      if (script.length == 4) {
        if (isSupported(script)) { r.push(script); }
      } else if (script.length == 6 && script.indexOf("~") == 4) {
        start = ATOZ.indexOf(script[3]);
        end = ATOZ.indexOf(script[5]);
        for (var i = start; i <= end; i++) {
          let c = script.substring(0, 3) + ATOZ[i];
          if (isSupported(c)) { r.push(c); }
        }
      }
    });
    return r;
  };
}
