// © 2020 Google, Ecma International

// Polyfill Intl.getSupportedUnits
if (Intl.getSupportedUnits == undefined) {
  Intl.getSupportedUnits = function() {
    let UNITS_IN_CLDR = [
      // DATA from CLDR
      // Generated by
      // file="https://raw.githubusercontent.com/unicode-org/cldr/master/common/validity/unit.xml"
      // curl $file 2> /dev/null | egrep "[a-z]-[a-z0-9]" | sed -e 's/^[[:space:]]*//g' | \
      //   sed -e 's/[[:space:]]*$//g' |sed -e 's/ /", "/g' |sed -e 's/$/",/g' |tr '\n' ' ' | \
      //   tr ' ' '\n'|cut -d '-' -f2-20 | sed -e 's/^/"/g' |sort -u | tr '\n' ' '
      "100-kilometer", "acre", "acre-foot", "ampere", "arc-minute", "arc-second",
      "astronomical-unit", "atmosphere", "bar", "barrel", "bit",
      "british-thermal-unit", "bushel", "byte", "calorie", "candela", "carat",
      "celsius", "centiliter", "centimeter", "century", "cubic-centimeter",
      "cubic-foot", "cubic-inch", "cubic-kilometer", "cubic-meter", "cubic-mile",
      "cubic-yard", "cup", "cup-metric", "dalton", "day", "day-person", "decade",
      "deciliter", "decimeter", "degree", "dot", "dot-per-centimeter",
      "dot-per-inch", "dunam", "earth-mass", "earth-radius", "electronvolt", "em",
      "fahrenheit", "fathom", "fluid-ounce", "fluid-ounce-imperial", "foodcalorie",
      "foot", "furlong", "g-force", "gallon", "gallon-imperial", "generic",
      "gigabit", "gigabyte", "gigahertz", "gigawatt", "gram", "hectare",
      "hectoliter", "hectopascal", "hertz", "horsepower", "hour", "inch", "inch-hg",
      "inch-ofhg", "item", "joule", "karat", "kelvin", "kilobit", "kilobyte",
      "kilocalorie", "kilogram", "kilohertz", "kilojoule", "kilometer",
      "kilometer-per-hour", "kilopascal", "kilowatt", "kilowatt-hour", "knot",
      "light-year", "liter", "liter-per-100-kilometer", "liter-per-100kilometers",
      "liter-per-kilometer", "lux", "megabit", "megabyte", "megahertz", "megaliter",
      "megapascal", "megapixel", "megawatt", "meter", "meter-per-second",
      "meter-per-second-squared", "meter-per-square-second", "metric-ton",
      "microgram", "micrometer", "microsecond", "mile", "mile-per-gallon",
      "mile-per-gallon-imperial", "mile-per-hour", "mile-scandinavian",
      "milliampere", "millibar", "milligram", "milligram-per-deciliter",
      "milliliter", "millimeter", "millimeter-of-mercury", "millimeter-ofhg",
      "millimole-per-liter", "millisecond", "milliwatt", "minute", "mole", "month",
      "month-person", "nanometer", "nanosecond", "nautical-mile", "newton",
      "newton-meter", "ofhg", "ohm", "ounce", "ounce-troy", "parsec",
      "part-per-million", "pascal", "percent", "permille", "permillion", "permyriad",
      "petabyte", "picometer", "pint", "pint-metric", "pixel",
      "pixel-per-centimeter", "pixel-per-inch", "point", "portion", "pound",
      "pound-foot", "pound-force", "pound-force-foot", "pound-force-per-square-inch",
      "pound-per-square-inch", "quart", "radian", "revolution", "second",
      "solar-luminosity", "solar-mass", "solar-radius", "square-centimeter",
      "square-foot", "square-inch", "square-kilometer", "square-meter",
      "square-mile", "square-yard", "stone", "tablespoon", "teaspoon", "terabit",
      "terabyte", "therm-us", "ton", "volt", "watt", "week", "week-person", "yard",
      "year", "year-person"
    ];
    const isSupported = function(unit) {
      try {
        let nf = new Intl.NumberFormat("en", {style: "unit", unit});
        let o = nf.resolvedOptions().unit;
        if (o == unit) { return true; }
        // console.log(unit + " is accepted but changed to " + o);
      } catch (e) {
        // console.log(unit + " is not supported");
      }
      return false;
    };
    var r = [];
    UNITS_IN_CLDR.forEach(function(unit) {
      if (isSupported(unit)) r.push(unit);
    });
    return r;
  };
}
